<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta http-equiv="X-UA-Compatible" content="IE=edge"/>';
echo '<meta name="viewport" content="width=device-width" />';
echo '<title>Wedding Restaurant</title>';
echo '<meta name="description" content="Vietnamese">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no">';
echo '<script type="text/javascript" src="js/critical.js"></script>';
echo '<link rel="stylesheet" href="css/cookieconsent.min.css">';
echo '<link href="https://fonts.googleapis.com/css?family=Montserrat:200,300,400,700,800" rel="stylesheet">';
echo '<link rel="stylesheet" href="css./styles.css">';
echo '<link rel="shortcut icon" type="image/x-icon" href="./images/logopage.png" />';
echo '<meta name="twitter:card" content="summary">';
echo '<meta name="twitter:site" content="@Weddingrestaurant">';
echo '<meta name="twitter:title" content="Wedding Restaurant">';
echo '<meta name="twitter:description" content="Steakhouse &amp; Grill | Almancil - Algarve, Portugal">';
echo '<meta name="twitter:creator" content="@Weddingrestaurant">';
echo '<meta name="twitter:image:src" content="images/image-shared.jpg">';
echo '<meta property="og:title" content="Wedding Restaurant" />';
echo '<meta property="og:type" content="website" />';
echo '<meta property="og:url" content="Home.html" />';
echo '<meta property="og:image" content="images/image-shared.jpg" />';
echo '<meta property="og:description" content="Vietnamese" />';
echo '<meta property="og:site_name" content="Wedding Natural" />';
echo '</head>';
echo '<body>';
echo '<header>';
echo '<div class="black-area">';
echo '<div class="container-fluid">';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<a href="tel:0123456789">';
echo '<img src="./images/phone-icon.png" alt="Phone">';
echo '<span class="hidden-xs">0123456789</span>';
echo '<span class="visible-xs-inline-block">Call now</span>';
echo '</a>';
echo '<a href="https://www.google.pt/maps/place/Tr%C6%B0%E1%BB%9Dng+%C4%90%E1%BA%A1i+h%E1%BB%8Dc+C%C3%B4ng+ngh%E1%BB%87+Th%C3%B4ng+tin+%C4%90HQG+TP.HCM/@10.8700089,106.8008654,17z/data=!3m1!4b1!4m5!3m4!1s0x317527587e9ad5bf:0xafa66f9c8be3c91!8m2!3d10.8700089!4d106.8030541" target="_blank" >';
echo '<img src="./images/directions-icon.png" alt="directions">';
echo '<span>directions</span>';
echo '</a>';
echo '<div class="social">';
echo '<span class="hidden-xs">follow us</span>';
echo '<a href="https://www.facebook.com/vietkitoo.01072001" target="_blank"><img src="./images/fb.png" alt="Facebook" class="hidden-xs"></a>';
echo '<a href="https://www.instagram.com/foodysaigon/" target="_blank"><img src="./images/instagram.png" alt="Instagram" class="hidden-xs"></a>';
echo '<a href="Login.html"> Login</a>';
echo '<a href="Register.html">Register</a>';
echo '<ul>';
echo '</ul>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="nav-menu">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<nav class="navbar navbar-default">';
echo '<!-- Brand and toggle get grouped for better mobile display -->';
echo '<div class="navbar-header">';
echo '<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">';
echo '<span class="sr-only">Toggle navigation</span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '<span class="icon-bar"></span>';
echo '</button>';
echo '<a class="navbar-brand" href="Home.html"><img src="./images/logo.png " alt="Parrilla natural"></a>';
echo '</div>';
echo '<!-- Collect the nav links, forms, and other content for toggling -->';
echo '<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">';
echo '<ul class="nav navbar-nav">';
echo '<li ><a href="Home.html">Home</a></li>';
echo '<li ><a href="Weddinghall.html">Wedding hall</a></li>';
echo '<li ><a href="Menu.html">Menu</a></li>';
echo '<li ><a href="Gallery.html">Gallery</a></li>';
echo '<li ><a href="Contacts.html">Contacts</a></li>';
echo '<li><a href="" class="btn btn-default" target="_blank">book now</a></li>';
echo '</ul>';
echo '<div class="visible-xs">';
echo '<hr class="hide-line">';
echo '<a href="https://www.google.pt/maps/place/Gourmet+Natural/@37.0722239,-8.0548575,17z/data=!3m1!4b1!4m5!3m4!1s0xd1ab47bf0ab0241:0x247897df028f1744!8m2!3d37.0722239!4d-8.0526688" target="_blank" class="btn-directins">';
echo '<img src="/static/images/directions-icon.png" alt="directions">';
echo '<span>directions</span>';
echo '</a>';
echo '<div class="social">';
echo '<a href="https://www.facebook.com/gourmetnatural/" target="_blank"><img src="/static/images/fb.png" alt="Facebook"></a>';
echo '<a href="https://www.instagram.com/gourmetnatural/" target="_blank"><img src="/static/images/instagram.png" alt="Instagram"></a>';
echo '<a href="https://www.tripadvisor.pt/Restaurant_Review-g262054-d1515988-Reviews-Gourmet_Natural_at_the_Ermitage-Almancil_Faro_District_Algarve.html" target="_blank"><img src="/static/images/trip.png" alt="Tripadvisor"></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<!-- /.navbar-collapse -->';
echo '</nav>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</header>';
echo '<div class="wrapper">';
echo '<div class="banner" style="background-image:url(images/SANH\ E.jpeg) !important; ">';
echo '<div class="container">';
echo '</div>';
echo '</div>';
echo '<div class="contacts">';
echo '<div class="container-full">';
echo '<div class="row">';
echo '<div class="col-sm-6 col-md-6">';
echo '<div class="google-map">';
echo '<div id="map_140333334297616_canvas" class="gm_fixes" style="width: 100%; height: 751px;"></div>';
echo '<a href="https://www.google.pt/maps/place/Gourmet+Natural/@37.0722239,-8.0548575,17z/data=!3m1!4b1!4m5!3m4!1s0xd1ab47bf0ab0241:0x247897df028f1744!8m2!3d37.0722239!4d-8.0526688" class="btn btn-primary" target="_blank"><img src="/static/images/directions-icon.png" alt="directions"><span>directions</span></a>';
echo '</div>';
echo '<script>';
echo 'function gm3b_140333334297616_init(){';
echo '';
echo 'var mapDiv = document.getElementById('map_140333334297616_canvas');';
echo 'var pos = new google.maps.LatLng(37.072224, -8.052626);';
echo 'var map = new google.maps.Map(mapDiv, {';
echo 'center: pos,';
echo 'zoom: 14,';
echo 'mapTypeId: google.maps.MapTypeId.ROADMAP,';
echo 'mapTypeControl: true,';
echo 'mapTypeControlOptions: {';
echo 'style: google.maps.MapTypeControlStyle.DEFAULT';
echo '},';
echo 'scrollwheel: false,';
echo 'draggable: true,';
echo '';
echo 'zoomControl: true,';
echo 'panControl: true,';
echo 'streetViewControl: true,';
echo 'scaleControl: true,';
echo 'rotateControl: true,';
echo '';
echo '});';
echo '';
echo '';
echo 'var marker = new google.maps.Marker({';
echo 'map: map,';
echo 'position: pos,';
echo '});';
echo '';
echo '';
echo '';
echo '';
echo '}';
echo '';
echo '';
echo '// required for ajax loading';
echo 'if(window.loaded==undefined){';
echo 'google.maps.event.addDomListener(window, 'load', gm3b_140333334297616_init);';
echo '} else {';
echo 'gm3b_140333334297616_init();';
echo '}';
echo '</script>';
echo '</div>';
echo '<div class="col-sm-6 col-md-6">';
echo '<div class="contact">';
echo '<h3>';
echo 'CALL NOW';
echo '</h3>';
echo '<p>';
echo '<a href="tel:0123456789">0123456789</a>';
echo '</p>';
echo '<h3>';
echo 'email';
echo '</h3>';
echo '<p>';
echo '<a href="mailto:info@gourmetnaturalrestaurant.com">info@gourmetnaturalrestaurant.com</a>';
echo '</p>';
echo '<h3>';
echo 'LOCATION';
echo '</h3>';
echo '<p>';
echo 'Ermitage, EM527 Ferrarias<br /> 8135-018 Almancil<br /> Algarve, Portugal';
echo '</p>';
echo '<h3>';
echo 'GPS';
echo '</h3>';
echo '<p>';
echo 'N 37.07231, W -8.05282';
echo '</p>';
echo '<h3>';
echo 'OPEN';
echo '</h3>';
echo '<p>';
echo 'Closed for the Winter';
echo '</p>';
echo '<p>';
echo '&nbsp;';
echo '</p>';
echo '<p>';
echo '&nbsp;';
echo '</p>';
echo '<a  href="https://widget.resdiary.com/(S(3bkufjrz4a4dp4s3k1gm04ox))/CheckAvailability.aspx?sourceKey=rd&id=4225" class="btn btn-primary  " target="_blank">book now</a>';
echo '</div>';
echo '<div class="job text-center">';
echo '<h3>';
echo 'work with us';
echo '</h3>';
echo '<p>';
echo 'Apply for a job on the Natural Group <a href="http://www.naturalgroup.com.pt/en/" target="_blank">website</a>';
echo '</p>';
echo '<a  href="http://www.naturalgroup.com.pt/en/contacts/" class="btn btn-primary  " target="_blank">Apply now</a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<footer>';
echo '<div class="green-area">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-sm-8">';
echo '<form action="/en/newsletter/subscribe/" method="POST" class="form newsletter-form" role="form" id="nsform">';
echo '<input type='hidden' name='csrfmiddlewaretoken' value='AN2YrFpEF4YcQCerDJPhcsuAld5qeZlc' />';
echo '<div class="">';
echo '<label for="id_email" class="label-control">Newsletter</label>';
echo '<input class="form-control" id="id_name" maxlength="250" name="name" placeholder=" name" type="text" />';
echo '<input class="form-control" id="id_email" maxlength="254" name="email" placeholder=" email" type="email" />';
echo '<div class="checkbox checkbox-inline  xs-checkbox-inline">';
echo '<input class="js-gdpr-check" id="id_gdpr_check" name="gdpr_check" type="checkbox" />';
echo '<label for="id_gdpr_check"';
echo 'class="label-control label-control--for-gdpr">';
echo '<span class="checkbox__input"></span>';
echo 'I have read and accept the <a target=_blank href="/en/privacy-policy/">Privacy policy</a>.';
echo '</label>';
echo '</div>';
echo '<div class="hp-failsafe" style="position:absolute; right:9000px;" ><input type="text" name="address" tabindex="-1" value="" autocomplete="off" ></div>';
echo '<input type="submit" value="" name="" class="btn btn-primary" onclick="ga('send', 'event', 'form', 'subscribe', 'newsletter')" />';
echo '<div class="checkbox checkbox-inline  hidden-xs">';
echo '<input class="js-gdpr-check js-gdpr-check" id="id_gdpr_check" name="gdpr_check" type="checkbox" />';
echo '<label for="id_gdpr_check"';
echo 'class="label-control label-control--for-gdpr">';
echo '<span class="checkbox__input"></span>';
echo 'I have read and accept the <a target=_blank href="/en/privacy-policy/">Privacy policy</a>.';
echo '</label>';
echo '</div>';
echo '</div>';
echo '</form>';
echo '<script type="text/javascript">';
echo '//GDPR Check';
echo '';
echo '$(document).ready(function(){';
echo 'var gdpr_checks = document.getElementsByClassName('js-gdpr-check');';
echo '';
echo '/**';
echo '* Enables a submit button if the provided GDPR check input is not checked.';
echo '* Disables it otherwise';
echo '*';
echo '* @param submitButton an HTML element for form submission';
echo '* @param GDPRCheck a checkbox that toggles the submit button's state';
echo '*/';
echo 'function updateSubmitButtonFromGDPR(submitButton, GDPRCheck) {';
echo 'submitButton.disabled = !GDPRCheck.checked;';
echo '}';
echo '';
echo 'Array.from(gdpr_checks).forEach(function (gdpr_check) {';
echo 'var submit_button = gdpr_check.form.querySelector('input[type=submit]');';
echo '';
echo 'updateSubmitButtonFromGDPR(submit_button, gdpr_check);';
echo '';
echo 'gdpr_check.addEventListener('change', function() {';
echo 'updateSubmitButtonFromGDPR(submit_button, gdpr_check);';
echo '});';
echo '});';
echo '});';
echo '</script>';
echo '</div>';
echo '<div class="col-sm-4 social text-right">';
echo '<span>follow us</span>';
echo '<a href="https://www.facebook.com/vietkitoo.01072001" target="_blank"><img src="images/facebook-white.png" alt="Facebook"></a>';
echo '<a href="https://www.instagram.com/foodysaigon/" target="_blank"><img src="images/insta-white.png" alt="Instagram"></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="black-area">';
echo '<div class="container">';
echo '<div class="row">';
echo '<div class="col-md-3">';
echo '<h5>Contacts</h5>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-md-12">';
echo '<div class="contact-footer">';
echo '<p>Việt khoai to</p>';
echo '<p>Quảng Nam</p>';
echo '</div>';
echo '<div class="contact-footer">';
echo '<a href="tel:+351289355271" class="phone-footer">0123456789</a>';
echo '<a href="mailto:info@gourmetnaturalrestaurant.com">FA@weddingrestaurant.com</a>';
echo '</div>';
echo '<div class="contact-footer">';
echo '<p>7 A.M - 19 P.M</p>';
echo '<p>&nbsp;</p>';
echo '<p>&nbsp;</p>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '<div class="row">';
echo '<div class="col-xs-12">';
echo '<div class="flex-content flex-content--footer">';
echo '<div class="contact-footer">';
echo '<a href="https://www.google.pt/maps/place/Tr%C6%B0%E1%BB%9Dng+%C4%90%E1%BA%A1i+h%E1%BB%8Dc+C%C3%B4ng+ngh%E1%BB%87+Th%C3%B4ng+tin+%C4%90HQG+TP.HCM/@10.8700089,106.8008654,17z/data=!3m1!4b1!4m5!3m4!1s0x317527587e9ad5bf:0xafa66f9c8be3c91!8m2!3d10.8700089!4d106.8030541" class="btn btn-default" target="_blank"><img src="images/directions-icon.png" alt="directions">directions</a>';
echo '</div>';
echo '<div class="contact-footer text-center">';
echo '<a href="https://www.livroreclamacoes.pt/inicio" target="_blank"><img src="/static/images/compaints_book.png" alt=""></a>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</div>';
echo '</footer>';
echo '<!-- script -->';
echo '<script src="js/app.js"></script>';
echo '<script src="css/cookieconsent.min.css"></script>';
echo '<script>';
echo 'window.addEventListener("load", function(){';
echo 'window.cookieconsent.initialise({';
echo '"palette": {';
echo '"popup": { "background": "#ffffff" },';
echo '"button": { "background": "#f48032" }';
echo '},';
echo '"showLink": true,';
echo '"content": {';
echo '"message": "Este site utiliza cookies para lhe proporcionar uma melhor experiência de navegação. Ao navegar estará a consentir a sua utilização.",';
echo '"dismiss": "OK",';
echo '"link": "Saber Mais",';
echo '"href": "/en/privacy-policy/"';
echo '}';
echo '})';
echo '});';
echo '</script>';
echo '</body>';
echo '</html>';
?>